export const classifyJson = [
  {
    title:'休闲零食',
    type:'lingshi',
    children:[
      {title:'进口零食',type:'jinkou'},
      {title:'面包糕点',type:'mianbao'},
      {title:'曲奇饼干',type:'binggan'},
    ]
  },
  {
    title:'乳饮酒水',
    type:'ruyin',
    children:[
      {title:'咖啡茶饮',type:'kafei'},
      {title:'奶粉麦片',type:'naifen'},
      {title:'风味牛奶',type:'niunai'},
    ]
  },
  {
    title:'日用百货',
    type:'baihuo',
    children:[
      {title:'收纳整理',type:'shouna'},
      {title:'毛巾拖鞋',type:'maojin'},
      {title:'生活电器',type:'dianqi'},
    ]
  },
  {
    title:'美容护肤',
    type:'hufu',
    children:[
      {title:'洗面奶乳',type:'ximian'},
      {title:'卸妆水乳',type:'xiezhuang'},
      {title:'口碑面膜',type:'mianmo'},
    ]
  },
]